class PubspecTemplate {
  static String buildPubspec(String appName) {
    return '''
name: $appName
description: A production-ready Flutter app generated by flutter_architecture_cli.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  rxdart: ^0.28.0
  provider: ^6.1.5+1
  connectivity_plus: ^7.0.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.4
  shared_preferences: ^2.5.4
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
''';
  }
}
